export { default as Header } from "./Header";
export { default as Navbar } from "./Navbar";
export { default as Main } from "./Main";
export { default as Footer } from "./Footer";
export { default as Test } from "./Test";
export { default as TestsList } from "./TestsList";
export { default as TestItem } from "./TestItem";
export { default as IrregularVerbsTest } from "./IrregularVerbsTest";
export { default as Results } from "./Results";
